// Mocks generated by Mockito 5.4.6 from annotations
// in feature_auth/test/unit/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core/core.dart' as _i4;
import 'package:feature_auth/src/domain/entities/otp_entity.dart' as _i8;
import 'package:feature_auth/src/domain/usecases/get_current_user_usecase.dart'
    as _i11;
import 'package:feature_auth/src/domain/usecases/login_with_email_password_usecase.dart'
    as _i2;
import 'package:feature_auth/src/domain/usecases/logout_usecase.dart' as _i10;
import 'package:feature_auth/src/domain/usecases/request_otp_usecase.dart'
    as _i7;
import 'package:feature_auth/src/domain/usecases/verify_otp_usecase.dart'
    as _i9;
import 'package:feature_auth/src/session/session_manager_impl.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_auth/shared_auth.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginWithEmailPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithEmailPasswordUseCase extends _i1.Mock
    implements _i2.LoginWithEmailPasswordUseCase {
  MockLoginWithEmailPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>> call(
    _i2.LoginWithEmailPasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>);
}

/// A class which mocks [RequestOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestOtpUseCase extends _i1.Mock implements _i7.RequestOtpUseCase {
  MockRequestOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i8.OtpEntity>> call(
    _i7.RequestOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i8.OtpEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i8.OtpEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i8.OtpEntity>>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i9.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>> call(
    _i9.VerifyOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i10.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i4.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i11.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.UserEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>>);
}

/// A class which mocks [SessionManagerImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManagerImpl extends _i1.Mock
    implements _i12.SessionManagerImpl {
  MockSessionManagerImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i5.AuthStatus> get authStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStatusStream),
            returnValue: _i3.Stream<_i5.AuthStatus>.empty(),
          )
          as _i3.Stream<_i5.AuthStatus>);

  @override
  _i5.AuthStatus get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i5.AuthStatus.checking,
          )
          as _i5.AuthStatus);

  @override
  _i3.Future<void> saveSession({
    required _i5.AuthTokenEntity? token,
    required _i5.UserEntity? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [], {#token: token, #user: user}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
