// Mocks generated by Mockito 5.4.6 from annotations
// in feature_auth/test/unit/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core/core.dart' as _i4;
import 'package:feature_auth/src/domain/entities/otp_entity.dart' as _i7;
import 'package:feature_auth/src/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_auth/shared_auth.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>
  loginWithEmailPassword({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>(
                    this,
                    Invocation.method(#loginWithEmailPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>);

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i7.OtpEntity>> requestOtp({
    required String? destination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [], {#destination: destination}),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i7.OtpEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i7.OtpEntity>>(
                    this,
                    Invocation.method(#requestOtp, [], {
                      #destination: destination,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i7.OtpEntity>>);

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>> verifyOtp({
    required String? destination,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #destination: destination,
              #code: code,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #destination: destination,
                      #code: code,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>);

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>> refreshToken({
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #refreshToken: refreshToken,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.AuthTokenEntity>>);

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>>.value(
                  _i6.dummyValue<_i4.Either<_i4.Failure, _i5.UserEntity>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i5.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>>.value(
              _i6.dummyValue<_i4.Either<_i4.Failure, _i4.Unit>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i4.Failure, _i4.Unit>>);
}
