import 'dart:io';

import 'package:mason/mason.dart';

/// Resolves `project_name` (used for `package:<name>/…` imports in the
/// generated tests) without asking for it.
///
/// `project_name` is not a brick var — mason would prompt for it, and it
/// is knowable: it is the `name:` of the project you are running
/// `mason make feature` inside. Resolution order:
///
///   1. `./pubspec.yaml` in the current directory — the normal case, run
///      from a project root;
///   2. the `FEATURE_PROJECT_NAME` environment variable — for generating
///      into a fresh directory with `-o`, where there is no `./pubspec.yaml`;
///   3. neither → stop with an explanatory error (a silent wrong value
///      would produce `package:my_app/…` imports that don't compile).
void run(HookContext context) {
  final fromPubspec = _nameFromPubspec(File('pubspec.yaml'));
  final fromEnv = Platform.environment['FEATURE_PROJECT_NAME']?.trim();
  final projectName =
      fromPubspec ?? (fromEnv?.isNotEmpty ?? false ? fromEnv : null);

  if (projectName == null) {
    context.logger.err(
      'Could not determine the project name.\n'
      'Run `mason make feature` from the root of a project generated by '
      'core_init (so ./pubspec.yaml is readable), or set FEATURE_PROJECT_NAME '
      'to the target project\'s pubspec name.',
    );
    exit(70);
  }

  context.vars = {...context.vars, 'project_name': projectName};
  final source =
      fromPubspec != null ? './pubspec.yaml' : r'$FEATURE_PROJECT_NAME';
  context.logger.info('project_name: "$projectName" (from $source)');
}

String? _nameFromPubspec(File pubspec) {
  if (!pubspec.existsSync()) return null;
  final match = RegExp(
    r'''^name:\s*['"]?([A-Za-z_][A-Za-z0-9_]*)['"]?''',
    multiLine: true,
  ).firstMatch(pubspec.readAsStringSync());
  return match?.group(1);
}
